SELECT * FROM USERS;
SELECT * FROM DOSEN;
SELECT * FROM MAHASISWA;
SELECT * FROM MATA_KULIAH;
SELECT * FROM RUANG_KELAS;
SELECT * FROM JADWAL_KULIAH;
SELECT * FROM SESI_ABSENSI;
SELECT * FROM ABSENSI;
SELECT * FROM NILAI;

-- view 
SELECT * FROM v_dosen_matkul_kehadiran;

-- index NIM
EXPLAIN PLAN FOR
SELECT * FROM MAHASISWA WHERE NIM = '31220002';
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

-- index kode matkul
EXPLAIN PLAN FOR
SELECT * FROM MATA_KULIAH WHERE KODE_MATKUL = 'PK301';
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);