SELECT * FROM USERS;
SELECT * FROM DOSEN;
SELECT * FROM MAHASISWA;
SELECT * FROM MATA_KULIAH;
SELECT * FROM RUANG_KELAS;
SELECT * FROM JADWAL_KULIAH;
SELECT * FROM SESI_ABSENSI;
SELECT * FROM ABSENSI;
SELECT * FROM NILAI;

SELECT * FROM v_dosen_matkul_kehadiran;

EXPLAIN PLAN FOR
SELECT * FROM MAHASISWA WHERE NIM = '2023001';

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
