-- =========================================================
-- 1. CREATE USER
-- =========================================================
CREATE USER uas IDENTIFIED BY uas
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

-- =========================================================
-- 2. GRANT PRIVILEGES
-- =========================================================
GRANT CREATE SESSION TO uas;
GRANT CREATE TABLE TO uas;
GRANT CREATE VIEW TO uas;
GRANT CREATE SEQUENCE TO uas;
GRANT CREATE TRIGGER TO uas;
GRANT CREATE PROCEDURE TO uas;
GRANT CREATE TYPE TO uas;
GRANT UNLIMITED TABLESPACE TO uas;

-- =========================================================
-- 3. GANTI SCHEMA
-- =========================================================
ALTER SESSION SET CURRENT_SCHEMA = uas;

------------------------------------------------------------
-- 4. DROP TABLES
------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ABSENSI CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE NILAI CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE SESI_ABSENSI CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE JADWAL_KULIAH CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE RUANG_KELAS CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE MATA_KULIAH CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE MAHASISWA CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE DOSEN CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

------------------------------------------------------------
-- 5. CREATE TABLES
------------------------------------------------------------

-- USERS
CREATE TABLE USERS (
    USER_ID        NUMBER PRIMARY KEY,
    USERNAME       VARCHAR2(50) UNIQUE NOT NULL,
    PASSWORD       VARCHAR2(255) NOT NULL,
    EMAIL          VARCHAR2(100),
    ROLE           VARCHAR2(20) CHECK (ROLE IN ('admin', 'dosen', 'mahasiswa')),
    IS_ACTIVE      NUMBER(1) DEFAULT 1,
    CREATED_AT     DATE DEFAULT SYSDATE,
    UPDATED_AT     DATE
);

-- DOSEN
CREATE TABLE DOSEN (
    DOSEN_ID       NUMBER PRIMARY KEY,
    USER_ID        NUMBER REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    NIP            VARCHAR2(30) UNIQUE NOT NULL,
    NAMA_LENGKAP   VARCHAR2(100) NOT NULL,
    EMAIL          VARCHAR2(100),
    NO_TELEPON     VARCHAR2(20),
    ALAMAT         VARCHAR2(200),
    TANGGAL_LAHIR  DATE,
    JENIS_KELAMIN  VARCHAR2(10),
    CREATED_AT     DATE DEFAULT SYSDATE,
    UPDATED_AT     DATE
);

-- MAHASISWA
CREATE TABLE MAHASISWA (
    MAHASISWA_ID   NUMBER PRIMARY KEY,
    USER_ID        NUMBER REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    NIM            VARCHAR2(30) UNIQUE NOT NULL,
    NAMA_LENGKAP   VARCHAR2(100) NOT NULL,
    EMAIL          VARCHAR2(100),
    NO_TELEPON     VARCHAR2(20),
    ALAMAT         VARCHAR2(200),
    TANGGAL_LAHIR  DATE,
    JENIS_KELAMIN  VARCHAR2(10),
    ANGKATAN       NUMBER(4),
    SEMESTER       NUMBER(2),
    STATUS         VARCHAR2(20) DEFAULT 'Aktif',
    CREATED_AT     DATE DEFAULT SYSDATE,
    UPDATED_AT     DATE
);

-- MATA KULIAH
CREATE TABLE MATA_KULIAH (
    MATKUL_ID      NUMBER PRIMARY KEY,
    KODE_MATKUL    VARCHAR2(20) UNIQUE NOT NULL,
    NAMA_MATKUL    VARCHAR2(100) NOT NULL,
    SKS            NUMBER(2),
    SEMESTER       NUMBER(2),
    DOSEN_ID       NUMBER REFERENCES DOSEN(DOSEN_ID),
    JENIS_MATKUL   VARCHAR2(30),
    DESKRIPSI      VARCHAR2(255),
    CREATED_AT     DATE DEFAULT SYSDATE,
    UPDATED_AT     DATE
);

-- RUANG KELAS
CREATE TABLE RUANG_KELAS (
    RUANG_ID       NUMBER PRIMARY KEY,
    KODE_RUANG     VARCHAR2(20) UNIQUE NOT NULL,
    NAMA_RUANG     VARCHAR2(100) NOT NULL,
    KAPASITAS      NUMBER(3),
    LOKASI         VARCHAR2(100),
    CREATED_AT     DATE DEFAULT SYSDATE,
    UPDATED_AT     DATE
);

-- JADWAL KULIAH
CREATE TABLE JADWAL_KULIAH (
    JADWAL_ID      NUMBER PRIMARY KEY,
    MATKUL_ID      NUMBER REFERENCES MATA_KULIAH(MATKUL_ID),
    DOSEN_ID       NUMBER REFERENCES DOSEN(DOSEN_ID),
    RUANG_ID       NUMBER REFERENCES RUANG_KELAS(RUANG_ID),
    HARI           VARCHAR2(15),
    JAM_MULAI      VARCHAR2(10),
    JAM_SELESAI    VARCHAR2(10),
    TAHUN_AJARAN   VARCHAR2(9),
    CREATED_AT     DATE DEFAULT SYSDATE,
    UPDATED_AT     DATE
);

-- SESI ABSENSI
CREATE TABLE SESI_ABSENSI (
    SESI_ID       NUMBER PRIMARY KEY,
    JADWAL_ID     NUMBER REFERENCES JADWAL_KULIAH(JADWAL_ID) ON DELETE CASCADE,
    DOSEN_ID      NUMBER REFERENCES DOSEN(DOSEN_ID) ON DELETE CASCADE,
    TANGGAL       DATE DEFAULT SYSDATE,
    STATUS        VARCHAR2(10) DEFAULT 'OPEN' CHECK (STATUS IN ('OPEN','CLOSED')),
    DIBUKA_PADA   DATE DEFAULT SYSDATE,
    DITUTUP_PADA  DATE
);

-- ABSENSI
CREATE TABLE ABSENSI (
    ABSENSI_ID         NUMBER PRIMARY KEY,
    SESI_ID            NUMBER REFERENCES SESI_ABSENSI(SESI_ID) ON DELETE CASCADE,
    JADWAL_ID          NUMBER REFERENCES JADWAL_KULIAH(JADWAL_ID) ON DELETE CASCADE,
    MAHASISWA_ID       NUMBER REFERENCES MAHASISWA(MAHASISWA_ID) ON DELETE CASCADE,
    TANGGAL            DATE DEFAULT SYSDATE,
    STATUS_KEHADIRAN   VARCHAR2(20) CHECK (STATUS_KEHADIRAN IN ('Hadir','Izin','Sakit','Alpa')),
    KETERANGAN         VARCHAR2(255),
    CREATED_AT         DATE DEFAULT SYSDATE,
    UPDATED_AT         DATE
);

-- NILAI
CREATE TABLE NILAI (
    NILAI_ID       NUMBER PRIMARY KEY,
    MAHASISWA_ID   NUMBER REFERENCES MAHASISWA(MAHASISWA_ID) ON DELETE CASCADE,
    MATKUL_ID      NUMBER REFERENCES MATA_KULIAH(MATKUL_ID) ON DELETE CASCADE,
    TAHUN_AJARAN   VARCHAR2(9),
    NILAI_TUGAS    NUMBER(5,2),
    NILAI_UTS      NUMBER(5,2),
    NILAI_UAS      NUMBER(5,2),
    NILAI_AKHIR    NUMBER(5,2),
    GRADE          VARCHAR2(2),
    STATUS         VARCHAR2(20) DEFAULT 'Aktif',
    CREATED_AT     DATE DEFAULT SYSDATE,
    UPDATED_AT     DATE
);

------------------------------------------------------------
-- 6. SEQUENCES
------------------------------------------------------------
CREATE SEQUENCE SEQ_USERS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DOSEN START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MAHASISWA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MATAKULIAH START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RUANG START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_JADWAL START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SESI_ABSENSI START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ABSENSI START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_NILAI START WITH 1 INCREMENT BY 1;

------------------------------------------------------------
-- 7. TRIGGERS (AUTO-INCREMENT)
------------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_USERS_PK
BEFORE INSERT ON USERS
FOR EACH ROW
WHEN (NEW.USER_ID IS NULL)
BEGIN
  SELECT SEQ_USERS.NEXTVAL INTO :NEW.USER_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_DOSEN_PK
BEFORE INSERT ON DOSEN
FOR EACH ROW
WHEN (NEW.DOSEN_ID IS NULL)
BEGIN
  SELECT SEQ_DOSEN.NEXTVAL INTO :NEW.DOSEN_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_MAHASISWA_PK
BEFORE INSERT ON MAHASISWA
FOR EACH ROW
WHEN (NEW.MAHASISWA_ID IS NULL)
BEGIN
  SELECT SEQ_MAHASISWA.NEXTVAL INTO :NEW.MAHASISWA_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_MATAKULIAH_PK
BEFORE INSERT ON MATA_KULIAH
FOR EACH ROW
WHEN (NEW.MATKUL_ID IS NULL)
BEGIN
  SELECT SEQ_MATAKULIAH.NEXTVAL INTO :NEW.MATKUL_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_RUANG_PK
BEFORE INSERT ON RUANG_KELAS
FOR EACH ROW
WHEN (NEW.RUANG_ID IS NULL)
BEGIN
  SELECT SEQ_RUANG.NEXTVAL INTO :NEW.RUANG_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_JADWAL_PK
BEFORE INSERT ON JADWAL_KULIAH
FOR EACH ROW
WHEN (NEW.JADWAL_ID IS NULL)
BEGIN
  SELECT SEQ_JADWAL.NEXTVAL INTO :NEW.JADWAL_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_SESI_ABSENSI_PK
BEFORE INSERT ON SESI_ABSENSI
FOR EACH ROW
WHEN (NEW.SESI_ID IS NULL)
BEGIN
  SELECT SEQ_SESI_ABSENSI.NEXTVAL INTO :NEW.SESI_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_ABSENSI_PK
BEFORE INSERT ON ABSENSI
FOR EACH ROW
WHEN (NEW.ABSENSI_ID IS NULL)
BEGIN
  SELECT SEQ_ABSENSI.NEXTVAL INTO :NEW.ABSENSI_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_NILAI_PK
BEFORE INSERT ON NILAI
FOR EACH ROW
WHEN (NEW.NILAI_ID IS NULL)
BEGIN
  SELECT SEQ_NILAI.NEXTVAL INTO :NEW.NILAI_ID FROM DUAL;
END;
/

COMMIT;
